services:
    vse.TopicImagePreview.listener:
        class: vse\TopicImagePreview\event\listener
        arguments:
            - '@config'
            - '@dbal.conn'
            - '@language'
        tags:
            - { name: event.listener }
